# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "transit_realtime.FeedMessage" do
    optional :header, :message, 1, "transit_realtime.FeedHeader"
    repeated :entity, :message, 2, "transit_realtime.FeedEntity"
  end
  add_message "transit_realtime.FeedHeader" do
    optional :gtfs_realtime_version, :string, 1
    optional :incrementality, :enum, 2, "transit_realtime.FeedHeader.Incrementality"
    optional :timestamp, :uint64, 3
  end
  add_enum "transit_realtime.FeedHeader.Incrementality" do
    value :FULL_DATASET, 0
    value :DIFFERENTIAL, 1
  end
  add_message "transit_realtime.FeedEntity" do
    optional :id, :string, 1
    optional :is_deleted, :bool, 2
    optional :trip_update, :message, 3, "transit_realtime.TripUpdate"
    optional :vehicle, :message, 4, "transit_realtime.VehiclePosition"
    optional :alert, :message, 5, "transit_realtime.Alert"
  end
  add_message "transit_realtime.TripUpdate" do
    optional :trip, :message, 1, "transit_realtime.TripDescriptor"
    optional :vehicle, :message, 3, "transit_realtime.VehicleDescriptor"
    repeated :stop_time_update, :message, 2, "transit_realtime.TripUpdate.StopTimeUpdate"
    optional :timestamp, :uint64, 4
    optional :delay, :int32, 5
  end
  add_message "transit_realtime.TripUpdate.StopTimeEvent" do
    optional :delay, :int32, 1
    optional :time, :int64, 2
    optional :uncertainty, :int32, 3
  end
  add_message "transit_realtime.TripUpdate.StopTimeUpdate" do
    optional :stop_sequence, :uint32, 1
    optional :stop_id, :string, 4
    optional :arrival, :message, 2, "transit_realtime.TripUpdate.StopTimeEvent"
    optional :departure, :message, 3, "transit_realtime.TripUpdate.StopTimeEvent"
    optional :schedule_relationship, :enum, 5, "transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship"
  end
  add_enum "transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship" do
    value :SCHEDULED, 0
    value :SKIPPED, 1
    value :NO_DATA, 2
  end
  add_message "transit_realtime.VehiclePosition" do
    optional :trip, :message, 1, "transit_realtime.TripDescriptor"
    optional :vehicle, :message, 8, "transit_realtime.VehicleDescriptor"
    optional :position, :message, 2, "transit_realtime.Position"
    optional :current_stop_sequence, :uint32, 3
    optional :stop_id, :string, 7
    optional :current_status, :enum, 4, "transit_realtime.VehiclePosition.VehicleStopStatus"
    optional :timestamp, :uint64, 5
    optional :congestion_level, :enum, 6, "transit_realtime.VehiclePosition.CongestionLevel"
    optional :occupancy_status, :enum, 9, "transit_realtime.VehiclePosition.OccupancyStatus"
  end
  add_enum "transit_realtime.VehiclePosition.VehicleStopStatus" do
    value :INCOMING_AT, 0
    value :STOPPED_AT, 1
    value :IN_TRANSIT_TO, 2
  end
  add_enum "transit_realtime.VehiclePosition.CongestionLevel" do
    value :UNKNOWN_CONGESTION_LEVEL, 0
    value :RUNNING_SMOOTHLY, 1
    value :STOP_AND_GO, 2
    value :CONGESTION, 3
    value :SEVERE_CONGESTION, 4
  end
  add_enum "transit_realtime.VehiclePosition.OccupancyStatus" do
    value :EMPTY, 0
    value :MANY_SEATS_AVAILABLE, 1
    value :FEW_SEATS_AVAILABLE, 2
    value :STANDING_ROOM_ONLY, 3
    value :CRUSHED_STANDING_ROOM_ONLY, 4
    value :FULL, 5
    value :NOT_ACCEPTING_PASSENGERS, 6
  end
  add_message "transit_realtime.Alert" do
    repeated :active_period, :message, 1, "transit_realtime.TimeRange"
    repeated :informed_entity, :message, 5, "transit_realtime.EntitySelector"
    optional :cause, :enum, 6, "transit_realtime.Alert.Cause"
    optional :effect, :enum, 7, "transit_realtime.Alert.Effect"
    optional :url, :message, 8, "transit_realtime.TranslatedString"
    optional :header_text, :message, 10, "transit_realtime.TranslatedString"
    optional :description_text, :message, 11, "transit_realtime.TranslatedString"
  end
  add_enum "transit_realtime.Alert.Cause" do
    value :PROTO3_DEFAULT_CAUSE, 0
    value :UNKNOWN_CAUSE, 1
    value :OTHER_CAUSE, 2
    value :TECHNICAL_PROBLEM, 3
    value :STRIKE, 4
    value :DEMONSTRATION, 5
    value :ACCIDENT, 6
    value :HOLIDAY, 7
    value :WEATHER, 8
    value :MAINTENANCE, 9
    value :CONSTRUCTION, 10
    value :POLICE_ACTIVITY, 11
    value :MEDICAL_EMERGENCY, 12
  end
  add_enum "transit_realtime.Alert.Effect" do
    value :PROTO3_DEFAULT_EFFECT, 0
    value :NO_SERVICE, 1
    value :REDUCED_SERVICE, 2
    value :SIGNIFICANT_DELAYS, 3
    value :DETOUR, 4
    value :ADDITIONAL_SERVICE, 5
    value :MODIFIED_SERVICE, 6
    value :OTHER_EFFECT, 7
    value :UNKNOWN_EFFECT, 8
    value :STOP_MOVED, 9
  end
  add_message "transit_realtime.TimeRange" do
    optional :start, :uint64, 1
    optional :end, :uint64, 2
  end
  add_message "transit_realtime.Position" do
    optional :latitude, :float, 1
    optional :longitude, :float, 2
    optional :bearing, :float, 3
    optional :odometer, :double, 4
    optional :speed, :float, 5
  end
  add_message "transit_realtime.TripDescriptor" do
    optional :trip_id, :string, 1
    optional :route_id, :string, 5
    optional :direction_id, :uint32, 6
    optional :start_time, :string, 2
    optional :start_date, :string, 3
    optional :schedule_relationship, :enum, 4, "transit_realtime.TripDescriptor.ScheduleRelationship"
  end
  add_enum "transit_realtime.TripDescriptor.ScheduleRelationship" do
    value :SCHEDULED, 0
    value :ADDED, 1
    value :UNSCHEDULED, 2
    value :CANCELED, 3
  end
  add_message "transit_realtime.VehicleDescriptor" do
    optional :id, :string, 1
    optional :label, :string, 2
    optional :license_plate, :string, 3
  end
  add_message "transit_realtime.EntitySelector" do
    optional :agency_id, :string, 1
    optional :route_id, :string, 2
    optional :route_type, :int32, 3
    optional :trip, :message, 4, "transit_realtime.TripDescriptor"
    optional :stop_id, :string, 5
  end
  add_message "transit_realtime.TranslatedString" do
    repeated :translation, :message, 1, "transit_realtime.TranslatedString.Translation"
  end
  add_message "transit_realtime.TranslatedString.Translation" do
    optional :text, :string, 1
    optional :language, :string, 2
  end
end

module TransitRealtime
  FeedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.FeedMessage").msgclass
  FeedHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.FeedHeader").msgclass
  FeedHeader::Incrementality = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.FeedHeader.Incrementality").enummodule
  FeedEntity = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.FeedEntity").msgclass
  TripUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripUpdate").msgclass
  TripUpdate::StopTimeEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripUpdate.StopTimeEvent").msgclass
  TripUpdate::StopTimeUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripUpdate.StopTimeUpdate").msgclass
  TripUpdate::StopTimeUpdate::ScheduleRelationship = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship").enummodule
  VehiclePosition = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.VehiclePosition").msgclass
  VehiclePosition::VehicleStopStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.VehiclePosition.VehicleStopStatus").enummodule
  VehiclePosition::CongestionLevel = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.VehiclePosition.CongestionLevel").enummodule
  VehiclePosition::OccupancyStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.VehiclePosition.OccupancyStatus").enummodule
  Alert = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.Alert").msgclass
  Alert::Cause = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.Alert.Cause").enummodule
  Alert::Effect = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.Alert.Effect").enummodule
  TimeRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TimeRange").msgclass
  Position = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.Position").msgclass
  TripDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripDescriptor").msgclass
  TripDescriptor::ScheduleRelationship = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TripDescriptor.ScheduleRelationship").enummodule
  VehicleDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.VehicleDescriptor").msgclass
  EntitySelector = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.EntitySelector").msgclass
  TranslatedString = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TranslatedString").msgclass
  TranslatedString::Translation = Google::Protobuf::DescriptorPool.generated_pool.lookup("transit_realtime.TranslatedString.Translation").msgclass
end
